{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "slaking.fullname" . }}-role
  labels:
    {{- include "slaking.labels" . | nindent 4 }}
  {{- with .Values.rbac.clusterRoleAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "slaking.fullname" . }}-role-binding
  labels:
    {{- include "slaking.labels" . | nindent 4 }}
  {{- with .Values.rbac.clusterRoleBindingAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "slaking.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "slaking.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }} 