apiVersion: v1
kind: Service
metadata:
  name: {{ include "slaking.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slaking.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "slaking.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slaking.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slaking.labels" . | nindent 4 }}
    component: metrics
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "slaking.selectorLabels" . | nindent 4 }} 