apiVersion: v2
name: slaking
description: A Kubernetes service that monitors workloads for annotations and sends filtered logs to Slack channels
type: application
version: 1.0.8
appVersion: "1.0.8"
keywords:
  - kubernetes
  - slack
  - logging
  - monitoring
  - operator
home: https://github.com/ElementTech/slaking
sources:
  - https://github.com/ElementTech/slaking
maintainers:
  - name: ElementTech
    email: elementtech@example.com
icon: https://raw.githubusercontent.com/ElementTech/slaking/main/icon.png
annotations:
  category: Monitoring
  licenses: MIT 