apiVersion: v1
kind: Service
metadata:
  name: slaking
  namespace: slaking
  labels:
    app: slaking
spec:
  selector:
    app: slaking
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: slaking-metrics
  namespace: slaking
  labels:
    app: slaking
    component: metrics
spec:
  selector:
    app: slaking
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP 