apiVersion: v1
kind: ServiceAccount
metadata:
  name: slaking
  namespace: slaking
  labels:
    app: slaking
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slaking-role
  labels:
    app: slaking
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slaking-role-binding
  labels:
    app: slaking
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: slaking-role
subjects:
- kind: ServiceAccount
  name: slaking
  namespace: slaking 